# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:

  test:
    working_directory: ~/
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test

      - codecov/upload:
          file: 'coverage'

  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "antimatter15@users.noreply.github.com"
            git config --global user.name "Kevin Kwok"
            echo "machine github.com login antimatter15 password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=antimatter15 CUSTOM_COMMIT_MESSAGE="[skip ci]" yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy-website:
        filters:
           branches:
             only:
               - master
